config/routes.rb
Rails.application.routes.draw do
  resources :breastfeedings
  resources :babies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
    has_many :breastfeedings, dependent: :destroy

    def to_s
        name
        
    end
    
    def total_drinking
        breastfeedings.sum(:quantity)    
    end

    def total_duration
        breastfeedings.sum(:duration)
    end

    def breastfeeding_times_today
        breastfeedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).count
    end

    def last_time_drinking
        if breastfeedings.count > 0
            breastfeedings.last.created_at
        else
            ''
        end
    end
    
    def breastfeeding_duration_today
        breastfeedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).sum(:duration)
    end

    def breastfeeding_quantity_today
        breastfeedings.where("created_at >= :start_at AND created_at <= :end_date", {start_at: Time.now.beginning_of_day, end_date: Time.now}).sum(:quantity)
    end
end

app/models/breastfeeding.rb
class Breastfeeding < ApplicationRecord
  belongs_to :baby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy]

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.all
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|
      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:name)
    end
end

app/controllers/breastfeedings_controller.rb
class BreastfeedingsController < ApplicationController
  before_action :set_breastfeeding, only: [:show, :edit, :update, :destroy]

  # GET /breastfeedings
  # GET /breastfeedings.json
  def index
    @breastfeedings = Breastfeeding.all
  end

  # GET /breastfeedings/1
  # GET /breastfeedings/1.json
  def show
  end

  # GET /breastfeedings/new
  def new
    @breastfeeding = Breastfeeding.new
    @babies = Baby.pluck :name, :id
  end

  # GET /breastfeedings/1/edit
  def edit
    @babies = Baby.pluck :name, :id
  end

  # POST /breastfeedings
  # POST /breastfeedings.json
  def create
    @breastfeeding = Breastfeeding.new(breastfeeding_params)

    respond_to do |format|
      if @breastfeeding.save
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully created.' }
        format.json { render :show, status: :created, location: @breastfeeding }
      else
        format.html { render :new }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breastfeedings/1
  # PATCH/PUT /breastfeedings/1.json
  def update
    respond_to do |format|
      if @breastfeeding.update(breastfeeding_params)
        format.html { redirect_to @breastfeeding, notice: 'Breastfeeding was successfully updated.' }
        format.json { render :show, status: :ok, location: @breastfeeding }
      else
        format.html { render :edit }
        format.json { render json: @breastfeeding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breastfeedings/1
  # DELETE /breastfeedings/1.json
  def destroy
    @breastfeeding.destroy
    respond_to do |format|
      format.html { redirect_to breastfeedings_url, notice: 'Breastfeeding was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_breastfeeding
      @breastfeeding = Breastfeeding.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def breastfeeding_params
      params.require(:breastfeeding).permit(:quantity, :duration, :baby_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/breastfeedings_helper.rb
module BreastfeedingsHelper
end

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby.errors.count, "error") %> prohibited this baby from being saved:</h2>

      <ul>
      <% baby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/babies/edit.html.erb
<h1>Editing Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Show', @baby %> |
<%= link_to 'Back', babies_path %>

app/views/babies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Babies</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Total cantidad</th>
        <th>Total tiempo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @babies.each do |baby| %>
      <tr>
        <td><%= baby.name %></td>
        <td><%= baby.total_drinking %></td>
        <td><%= baby.total_duration %></td>
        <td><%= link_to 'Show', baby %></td>
        <td><%= link_to 'Edit', edit_baby_path(baby) %></td>
        <td><%= link_to 'Destroy', baby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby', new_baby_path %>

app/views/babies/new.html.erb
<h1>New Baby</h1>

<%= render 'form', baby: @baby %>

<%= link_to 'Back', babies_path %>

app/views/babies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baby.name %>
</p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Veces que ha tomado</th>
      <th>Fecha de la ultim vez</th>
      <th>Cuanto tiempo</th>
       <th>Cuanto ha bebido hoy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @baby.breastfeeding_times_today %></td>
        <td><%= @baby.last_time_drinking %></td>
        <td><%= @baby.breastfeeding_duration_today %></td>
         <td><%= @baby.breastfeeding_quantity_today %></td>
      </tr>
  </tbody>
   </table>

<%= link_to 'Edit', edit_baby_path(@baby) %> |
<%= link_to 'Back', babies_path %>

app/views/breastfeedings/_form.html.erb
<%= form_with(model: breastfeeding, local: true) do |form| %>
  <% if breastfeeding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(breastfeeding.errors.count, "error") %> prohibited this breastfeeding from being saved:</h2>

      <ul>
      <% breastfeeding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, :id, :breastfeeding_quantity%>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration, :id, :breastfeeding_duration %>
  </div>

  <div class="field">
    <%= form.label :baby_id %>
    <%= form.select :baby_id options_for_select(@babies)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/breastfeedings/edit.html.erb
<h1>Editing Breastfeeding</h1>

<%= render 'form', breastfeeding: @breastfeeding %>

<%= link_to 'Show', @breastfeeding %> |
<%= link_to 'Back', breastfeedings_path %>

app/views/breastfeedings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breastfeedings</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Duration</th>
      <th>Baby</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breastfeedings.each do |breastfeeding| %>
      <tr>
        <td><%= breastfeeding.quantity %></td>
        <td><%= breastfeeding.duration %></td>
        <td><%= breastfeeding.baby %></td>
        <td><%= link_to 'Show', breastfeeding %></td>
        <td><%= link_to 'Edit', edit_breastfeeding_path(breastfeeding) %></td>
        <td><%= link_to 'Destroy', breastfeeding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breastfeeding', new_breastfeeding_path %>

app/views/breastfeedings/new.html.erb
<h1>New Breastfeeding</h1>

<%= render 'form', breastfeeding: @breastfeeding %>

<%= link_to 'Back', breastfeedings_path %>

app/views/breastfeedings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @breastfeeding.quantity %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @breastfeeding.duration %>
</p>

<p>
  <strong>Baby:</strong>
  <%= @breastfeeding.baby %>
</p>

<%= link_to 'Edit', edit_breastfeeding_path(@breastfeeding) %> |
<%= link_to 'Back', breastfeedings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EsposaApu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
  </head>

  <body>
  <div class="container">
    <%= yield %>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
  </body>
</html>